<?php

namespace ContainerAVBwVu9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobAdminControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Administrateur\JobAdminController' shared autowired service.
     *
     * @return \App\Controller\Administrateur\JobAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Administrateur'.\DIRECTORY_SEPARATOR.'JobAdminController.php';

        $container->services['App\\Controller\\Administrateur\\JobAdminController'] = $instance = new \App\Controller\Administrateur\JobAdminController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\Administrateur\\JobAdminController', $container));

        return $instance;
    }
}
