<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAVBwVu9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAVBwVu9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAVBwVu9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAVBwVu9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAVBwVu9\App_KernelProdContainer([
    'container.build_hash' => 'AVBwVu9',
    'container.build_id' => 'bda007fb',
    'container.build_time' => 1607352328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAVBwVu9');
