<?php

namespace ContainerXNwux9n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticlesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._LLvGt6.App\Entity\Articles' shared service.
     *
     * @return \App\Entity\Articles
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._LLvGt6": it references class "App\\Entity\\Articles" but no such service exists.');
    }
}
