<?php

namespace ContainerT1MqMo6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.17qL2MO.App\Entity\Jobs' shared service.
     *
     * @return \App\Entity\Jobs
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.17qL2MO": it references class "App\\Entity\\Jobs" but no such service exists.');
    }
}
