<?php

namespace ContainerFT7x7Zx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZPKOpxxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zPKOpxx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zPKOpxx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articlesRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
            'jobsRepository' => ['privates', 'App\\Repository\\JobsRepository', 'getJobsRepositoryService', true],
        ], [
            'articlesRepository' => 'App\\Repository\\ArticlesRepository',
            'jobsRepository' => 'App\\Repository\\JobsRepository',
        ]);
    }
}
