<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE2DzD71\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE2DzD71/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE2DzD71.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE2DzD71\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE2DzD71\App_KernelDevDebugContainer([
    'container.build_hash' => 'E2DzD71',
    'container.build_id' => '74df191f',
    'container.build_time' => 1607529999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE2DzD71');
