<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7s79x5g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7s79x5g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7s79x5g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7s79x5g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7s79x5g\App_KernelDevDebugContainer([
    'container.build_hash' => '7s79x5g',
    'container.build_id' => '2a39bc94',
    'container.build_time' => 1607525532,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7s79x5g');
