<?php

namespace ContainerE2DzD71;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FmegLzHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FmegLzH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FmegLzH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profile' => ['privates', '.errored..service_locator.FmegLzH.App\\Entity\\Profile', NULL, 'Cannot autowire service ".service_locator.FmegLzH": it references class "App\\Entity\\Profile" but no such service exists.'],
        ], [
            'profile' => 'App\\Entity\\Profile',
        ]);
    }
}
